
doctrine:
    orm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            timestampable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Timestampable
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Timestampable"