lexik_jwt_authentication:
    # private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    # public_key_path: '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    secret_key:     '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%' # required for token creation
    public_key:     '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'  # required for token verification
    pass_phrase:    '%env(JWT_PASSPHRASE)%'
    token_ttl:      3600
