login_check:
    path:     /api/login_check
    methods:  [POST]

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api_platform:
    resource: .
    type: api_platform
    prefix: /api


controllers:
    resource: ../../Controller/
    type: annotation


