### OSWIS Core - routes

### Endpoint for log in by front-end app.
login_check:
    path:     /api/login_check
    methods:  [POST]

### Endpoint for refresh of JWT token.
gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

### API Platform settings.
api_platform:
    resource: .
    type: api_platform
    prefix: /api

### Controller folder.
controllers:
    resource: ../../Controller/
    type: annotation

### Endpoint for user activation requests.
oswis_org_oswis_core_app_user_activation:
    controller: oswis_org_oswis_core.app_user_controller::appUserActivationAction
    path: "/app-user-activation/{token}"

oswis_org_oswis_core_app_user_register_root:
    controller: oswis_org_oswis_core.app_user_controller::registerRoot
    path: "/internal/register-root"

oswis_org_oswis_core_web_portal:
    controller: oswis_org_oswis_core.portal_web_controller::portal
    path: "/portal"

### Homepage page.
oswis_org_oswis_core_homepage_action:
    controller: oswis_org_oswis_core.homepage_web_controller::homepageAction
    path: "/{page}"
    defaults:
        page: 0
    requirements:
        page: '\d+'

### GDPR page (for forms etc.).
oswis_org_oswis_core_gdpr_action:
    controller: oswis_org_oswis_core.gdpr_web_controller::gdprAction
    path: "/gdpr"
