### OSWIS Core - routes

### Endpoint for log in by front-end app.
login_check:
    path:     /api/login_check
    methods:  [POST]

### Endpoint for refresh of JWT token.
gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

### API Platform settings.
api_platform:
    resource: .
    type: api_platform
    prefix: /api

### Controller folder.
controllers:
    resource: ../../Controller/
    type: annotation

### Endpoint for user activation requests.
oswis_org_oswis_core_app_user_activation:
    controller: oswis_org_oswis_core.app_user_controller::appUserActivationAction
    path: "/app-user-activation/{token}"

oswis_org_oswis_core_app_user_register_root:
    controller: oswis_org_oswis_core.app_user_controller::registerRoot
    path: "/internal/register-root"

oswis_org_oswis_core_web_portal:
    controller: oswis_org_oswis_core.portal_web_controller::portal
    path: "/portal/{foo?}"
    requirements:
        foo: .+

oswis_org_oswis_core_web_admin:
    controller: oswis_org_oswis_core.admin_web_controller::admin
    path: "/admin/{foo?}"
    requirements:
        foo: .+

### Homepage page.
oswis_org_oswis_core_homepage_action:
    controller: oswis_org_oswis_core.homepage_web_controller::homepageAction
    path: "/{page}"
    defaults:
        page: 0
    requirements:
        page: '\d+'

### GDPR page (for forms etc.).
oswis_org_oswis_core_gdpr_action:
    controller: oswis_org_oswis_core.gdpr_web_controller::gdprAction
    path: "/gdpr"

oswis_org_oswis_core_internal_action_clear_cache:
    controller: oswis_org_oswis_core.internal_actions_web_controller::clearCache
    path: "/internal/actions/clear_cache"

oswis_org_oswis_core_site_web_manifest_action:
    controller: oswis_org_oswis_core.site_web_manifest_controller::siteWebManifest
    path: "/site.webmanifest"

oswis_org_oswis_core_browserconfig_action:
    controller: oswis_org_oswis_core.site_web_manifest_controller::browserconfig
    path: "/browserconfig.xml"

oswis_org_oswis_core_robots_action:
    controller: oswis_org_oswis_core.site_web_manifest_controller::robots
    path: "/robots.txt"

oswis_org_oswis_core_sitemap_index_action:
    controller: oswis_org_oswis_core.site_map_web_controller::sitemapIndex
    path: "/sitemap_index.xml"

oswis_org_oswis_core_sitemap_core_action:
    controller: oswis_org_oswis_core.site_map_web_controller::sitemapCore
    path: "/sitemap_core.xml"

oswis_org_oswis_rss:
    controller: oswis_org_oswis_core.rss_feed_controller::showRss
    path: "/rss"

oswis_org_oswis_sitemap_core_xml:
    controller: oswis_org_oswis_core.site_map_web_controller::showSitemapXml
    path: "/sitemap_core.xml"

oswis_org_oswis_sitemap_index_xml:
    controller: oswis_org_oswis_core.site_map_web_controller::showSitemapIndexXml
    path: "/sitemap_index.xml"

oswis_org_oswis_sitemap_xsl:
    controller: oswis_org_oswis_core.site_map_web_controller::showSitemapXsl
    path: "/sitemap.xsl"

oswis_org_oswis_sitemap_xml_redir:
    controller: oswis_org_oswis_core.site_map_web_controller::sitemapRedir
    path: "/sitemap.xml"

#oswis_org_oswis_sitemap:
#    controller: oswis_org_oswis_core.site_map_controller::showSitemap
#    path: "/sitemap"


