### OSWIS Core - routes

### Endpoint for API log in by front-end app.
login_check:
    path:     /api/login_check
    methods:  [POST]

### Endpoint for refresh of JWT token.
gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

### API Platform settings.
api_platform:
    resource: .
    type: api_platform
    prefix: /api

### Controller folder.
controllers:
    resource: ../../Controller/
    type: annotation

### Endpoint for token processing.
oswis_org_oswis_core_app_user_process_token:
    controller: oswis_org_oswis_core.app_user_controller::processToken
    path: "/uzivatel/token/{token}/{appUserId}"
    requirements:
        appUserId: '\d+'

### Endpoint for user activation request.
oswis_org_oswis_core_app_user_activation_request:
    controller: oswis_org_oswis_core.app_user_controller::activationRequest
    path: "/uzivatel/aktivace"

### Endpoint for password change request.
oswis_org_oswis_core_app_user_password_change_request:
    controller: oswis_org_oswis_core.app_user_controller::passwordChangeRequest
    path: "/uzivatel/zmena-hesla/{token}/{appUserId}"
    requirements:
        appUserId: '\d+'

oswis_org_oswis_core_app_user_register_root:
    controller: oswis_org_oswis_core.app_user_controller::registerRoot
    path: "/internal/register-root"

oswis_org_oswis_core_portal:
    controller: oswis_org_oswis_core.portal_web_controller::portal
    path: "/portal/{foo?}"
    requirements:
        foo: .+

oswis_org_oswis_core_admin:
    controller: oswis_org_oswis_core.admin_web_controller::admin
    path: "/admin/{foo?}"
    requirements:
        foo: .+

### Homepage page.
oswis_org_oswis_core_homepage_action:
    controller: oswis_org_oswis_core.homepage_web_controller::homepageAction
    path: "/{page}"
    defaults:
        page: 0
    requirements:
        page: '\d+'

oswis_org_oswis_core_admin_site_web_manifest:
    controller: oswis_org_oswis_core.admin_web_controller::adminSiteWebManifest
    path: "/admin/site.webmanifest"

### GDPR page (for forms etc.).
oswis_org_oswis_core_gdpr_action:
    controller: oswis_org_oswis_core.gdpr_web_controller::gdprAction
    path: "/gdpr"

oswis_org_oswis_core_internal_action_clear_cache:
    controller: oswis_org_oswis_core.internal_actions_web_controller::clearCache
    path: "/internal/actions/clear_cache"

oswis_org_oswis_core_site_web_manifest:
    controller: oswis_org_oswis_core.site_web_manifest_controller::showSiteWebManifest
    path: "/site.webmanifest"

oswis_org_oswis_core_browserconfig_xml:
    controller: oswis_org_oswis_core.site_web_manifest_controller::showBrowserConfigXml
    path: "/browserconfig.xml"

oswis_org_oswis_core_robots_txt:
    controller: oswis_org_oswis_core.site_web_manifest_controller::showRobotsTxt
    path: "/robots.txt"

oswis_org_oswis_core_rss_xml:
    controller: oswis_org_oswis_core.rss_feed_controller::showRssXml
    path: "/rss.xml"

oswis_org_oswis_core_rss_redirect:
    controller: oswis_org_oswis_core.rss_feed_controller::rssRedirect
    path: "/rss"

oswis_org_oswis_core_rss_css:
    controller: oswis_org_oswis_core.rss_feed_controller::showRssCss
    path: "/rss.css"

oswis_org_oswis_core_sitemap_xml:
    controller: oswis_org_oswis_core.site_map_web_controller::showSitemapXml
    path: "/sitemap.xml"

oswis_org_oswis_core_sitemap_xsl:
    controller: oswis_org_oswis_core.site_map_web_controller::showSitemapXsl
    path: "/sitemap.xsl"

oswis_org_oswis_core_sitemap_redirect:
    controller: oswis_org_oswis_core.site_map_web_controller::sitemapRedirect
    path: "/sitemap"

