### OSWIS Core - services

parameters:
    locale: 'cs'
    doctrine_behaviors_blameable_user_entity: OswisOrg\OswisCoreBundle\Entity\AppUser

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ### Search Filter
    oswis_org_oswis_core.search_filter:
        class: OswisOrg\OswisCoreBundle\Filter\SearchFilter
        autowire: true
        tags: [ { name: 'api_platform.filter', id: 'search' } ]
        public: true
    OswisOrg\OswisCoreBundle\Filter\SearchFilter:
        alias: oswis_org_oswis_core.search_filter
        public: true

    ### OSWIS Core Settings Provider
    oswis_org_oswis_core.oswis_core_settings_provider:
        class: OswisOrg\OswisCoreBundle\Provider\OswisCoreSettingsProvider
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Provider\OswisCoreSettingsProvider:
        alias: oswis_org_oswis_core.oswis_core_settings_provider
        public: true

    ### AppUser Action Request
    oswis_org_oswis_core.app_user_action_request:
        class: OswisOrg\OswisCoreBundle\Api\Dto\AppUserActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Api\Dto\AppUserActionRequest:
        alias: oswis_org_oswis_core.app_user_action_request
        public: true

    ### AppUser Provider
    OswisOrg\OswisCoreBundle\Security\AppUserProvider:
        class: OswisOrg\OswisCoreBundle\Security\AppUserProvider
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.app_user_repository'

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
        public: true

    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
        public: true

    ####
    #### SERVICES
    ####

    oswis_org_oswis_core.app_user_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserService
        autowire: true
        public: true
        arguments:
            - '@security.password_encoder'
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@oswis_org_oswis_core.app_user_token_service'
            - '@oswis_org_oswis_core.app_user_mail_service'
            - '@oswis_org_oswis_core.app_user_type_service'
            - '@oswis_org_oswis_core.app_user_repository'
    OswisOrg\OswisCoreBundle\Service\AppUserService:
        alias: oswis_org_oswis_core.app_user_service
        public: true

    ### AppUser Defaults Service
    oswis_org_oswis_core.app_user_defaults_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserDefaultsService
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
            - '@oswis_org_oswis_core.app_user_type_service'
            - '@oswis_org_oswis_core.app_user_role_service'
            - '@oswis_org_oswis_core.app_user_service'
    OswisOrg\OswisCoreBundle\Service\AppUserDefaultsService:
        alias: oswis_org_oswis_core.app_user_defaults_service
        public: true

    ### AppUser Token Service
    oswis_org_oswis_core.app_user_token_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserTokenService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCoreBundle\Service\AppUserTokenService:
        alias: oswis_org_oswis_core.app_user_token_service
        public: true

    ### Mail Service
    oswis_org_oswis_core.mail_service:
        class: OswisOrg\OswisCoreBundle\Service\MailService
        autowire: true
        public: true
        arguments:
            - '@monolog.logger'
            - '@mailer.mailer'
            - '@doctrine.orm.entity_manager'
    OswisOrg\OswisCoreBundle\Service\MailService:
        alias: oswis_org_oswis_core.mail_service
        public: true

    ### AppUser Mail Service
    oswis_org_oswis_core.app_user_mail_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserMailService
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.mail_service'
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_core.app_user_mail_group_repository'
            - '@oswis_org_oswis_core.app_user_mail_category_repository'
            - '@oswis_org_oswis_core.app_user_mail_repository'
    OswisOrg\OswisCoreBundle\Service\AppUserMailService:
        alias: oswis_org_oswis_core.app_user_mail_service
        public: true

    ### AppUser Role Service
    oswis_org_oswis_core.app_user_role_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserRoleService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@oswis_org_oswis_core.app_user_role_repository'
    OswisOrg\OswisCoreBundle\Service\AppUserRoleService:
        alias: oswis_org_oswis_core.app_user_role_service
        public: true

    ### AppUser Form Service
    oswis_org_oswis_core.app_user_type_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@oswis_org_oswis_core.app_user_type_repository'
    OswisOrg\OswisCoreBundle\Service\AppUserTypeService:
        alias: oswis_org_oswis_core.app_user_type_service
        public: true

    oswis_org_oswis_core.export_service:
        class: OswisOrg\OswisCoreBundle\Service\ExportService
        autowire: true
        public: true
        arguments:
            - '@monolog.logger'
            - '@twig'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\Service\ExportService:
        alias: oswis_org_oswis_core.export_service
        public: true

    oswis_org_oswis_core.site_map_service:
        class: OswisOrg\OswisCoreBundle\Service\SiteMapService
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Service\SiteMapService:
        alias: oswis_org_oswis_core.site_map_service
        public: true

    oswis_org_oswis_core.core_site_map_extender:
        class: OswisOrg\OswisCoreBundle\Extender\CoreSitemapExtender
        autowire: true
        public: true
        arguments:
            - '@router.default'
        tags:
            - 'oswis.site_map_extender'
    OswisOrg\OswisCoreBundle\Extender\CoreSitemapExtender:
        alias: oswis_org_oswis_core.core_site_map_extender
        public: true

    ###
    ### REPOSITORY
    ###

    oswis_org_oswis_core.app_user_repository:
        class: OswisOrg\OswisCoreBundle\Repository\AppUserRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - '@doctrine.repository_service'
    OswisOrg\OswisCoreBundle\Repository\AppUserRepository:
        alias: oswis_org_oswis_core.app_user_repository
        public: true

    oswis_org_oswis_core.app_user_type_repository:
        class: OswisOrg\OswisCoreBundle\Repository\AppUserTypeRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - '@doctrine.repository_service'
    OswisOrg\OswisCoreBundle\Repository\AppUserTypeRepository:
        alias: oswis_org_oswis_core.app_user_type_repository
        public: true

    oswis_org_oswis_core.app_user_role_repository:
        class: OswisOrg\OswisCoreBundle\Repository\AppUserRoleRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - '@doctrine.repository_service'
    OswisOrg\OswisCoreBundle\Repository\AppUserRoleRepository:
        alias: oswis_org_oswis_core.app_user_role_repository
        public: true

    oswis_org_oswis_core.app_user_token_repository:
        class: OswisOrg\OswisCoreBundle\Repository\AppUserTokenRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - '@doctrine.repository_service'
    OswisOrg\OswisCoreBundle\Repository\AppUserTokenRepository:
        alias: oswis_org_oswis_core.app_user_token_repository
        public: true

    oswis_org_oswis_core.app_user_mail_category_repository:
        class: OswisOrg\OswisCoreBundle\Repository\AppUserMailCategoryRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - '@doctrine.repository_service'
    OswisOrg\OswisCoreBundle\Repository\AppUserMailCategoryRepository:
        alias: oswis_org_oswis_core.app_user_mail_category_repository
        public: true

    oswis_org_oswis_core.app_user_mail_repository:
        class: OswisOrg\OswisCoreBundle\Repository\AppUserMailRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - '@doctrine.repository_service'
    OswisOrg\OswisCoreBundle\Repository\AppUserMailRepository:
        alias: oswis_org_oswis_core.app_user_mail_repository
        public: true

    oswis_org_oswis_core.app_user_mail_group_repository:
        class: OswisOrg\OswisCoreBundle\Repository\AppUserMailGroupRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - '@doctrine.repository_service'
    OswisOrg\OswisCoreBundle\Repository\AppUserMailGroupRepository:
        alias: oswis_org_oswis_core.app_user_mail_group_repository
        public: true

    oswis_org_oswis_core.twig_template_repository:
        class: OswisOrg\OswisCoreBundle\Repository\TwigTemplateRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - '@doctrine.repository_service'
    OswisOrg\OswisCoreBundle\Repository\TwigTemplateRepository:
        alias: oswis_org_oswis_core.twig_template_repository
        public: true


    ####
    #### SUBSCRIBERS
    ####

    ### AppUser Action Subscriber
    oswis_org_oswis_core.app_user_action_subscriber:
        class: OswisOrg\OswisCoreBundle\Api\EventSubscriber\AppUserActionSubscriber
        autowire: true
        public: true
        tags: [ { name: 'kernel.view'} ]
        arguments:
            - '@oswis_org_oswis_core.app_user_service'
    OswisOrg\OswisCoreBundle\Api\EventSubscriber\AppUserActionSubscriber:
        alias: oswis_org_oswis_core.app_user_action_subscriber
        public: true

    ### Export Subscriber
    oswis_org_oswis_core.export_subscriber:
        class: OswisOrg\OswisCoreBundle\EventSubscriber\ExportSubscriber
        autowire: true
        tags: [ { name: 'kernel.view'} ]
        public: true
        arguments:
            - '@oswis_org_oswis_core.export_service'
    OswisOrg\OswisCoreBundle\EventSubscriber\ExportSubscriber:
        alias: oswis_org_oswis_core.app_user_action_subscriber
        public: true

    ### Mailer Subscriber
    oswis_org_oswis_core.mailer_subscriber:
        class: OswisOrg\OswisCoreBundle\EventSubscriber\MailerSubscriber
        autowire: true
        public: true
        tags: ['kernel.event_subscriber']
        arguments:
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\EventSubscriber\MailerSubscriber:
        alias: oswis_org_oswis_core.mailer_subscriber
        public: true

    ### AppUser Subscriber
    oswis_org_oswis_core.app_user_subscriber:
        class: OswisOrg\OswisCoreBundle\EventSubscriber\AppUserSubscriber
        autowire: true
        tags: [ { name: 'kernel.view'} ]
        public: true
        arguments:
            - '@oswis_org_oswis_core.app_user_service'
    OswisOrg\OswisCoreBundle\EventSubscriber\AppUserSubscriber:
        alias: oswis_org_oswis_core.app_user_subscriber
        public: true




    ####
    #### TWIG
    ####
    oswis_org_oswis_core.twig.image_extension:
        class: OswisOrg\OswisCoreBundle\Twig\Extension\ImageExtension
        public: true
        tags:
            - { name: twig.extension }
    oswis_org_oswis_core.twig.database_loader:
        class: OswisOrg\OswisCoreBundle\Twig\Loader\DatabaseLoader
        public: true
        arguments:
            - '@oswis_org_oswis_core.twig_template_repository'
        tags:
            - { name: twig.loader }





    ####
    #### UTILS
    ####
    ### COLOR UTILS
    oswis_org_oswis_core.oswis_core_color_utils:
        class: OswisOrg\OswisCoreBundle\Utils\ColorUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\ColorUtils:
        alias: oswis_org_oswis_core.oswis_core_color_utils
        public: true

    ### DateTime UTILS
    oswis_org_oswis_core.oswis_core_date_time_utils:
        class: OswisOrg\OswisCoreBundle\Utils\DateTimeUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\DateTimeUtils:
        alias: oswis_org_oswis_core.oswis_core_date_time_utils
        public: true

    ### Email UTILS
    oswis_org_oswis_core.oswis_core_email_utils:
        class: OswisOrg\OswisCoreBundle\Utils\EmailUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\EmailUtils:
        alias: oswis_org_oswis_core.oswis_core_email_utils
        public: true

    ### File UTILS
    oswis_org_oswis_core.oswis_core_file_utils:
        class: OswisOrg\OswisCoreBundle\Utils\FileUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\FileUtils:
        alias: oswis_org_oswis_core.oswis_core_file_utils
        public: true

    ### SourceCode UTILS
    oswis_org_oswis_core.oswis_core_source_code_utils:
        class: OswisOrg\OswisCoreBundle\Utils\SourceCodeUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\SourceCodeUtils:
        alias: oswis_org_oswis_core.oswis_core_source_code_utils
        public: true


    ### String UTILS
    oswis_org_oswis_core.oswis_core_source_string_utils:
        class: OswisOrg\OswisCoreBundle\Utils\StringUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\StringUtils:
        alias: oswis_org_oswis_core.oswis_core_source_string_utils
        public: true



    ####
    #### WEB
    ####
    ### AppUser Controller
    oswis_org_oswis_core.app_user_controller:
        class: OswisOrg\OswisCoreBundle\Controller\AppUserController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.app_user_service'
    OswisOrg\OswisCoreBundle\Controller\AppUserController:
        alias: oswis_org_oswis_core.app_user_controller
        public: true

    ### Homepage Web Controller
    oswis_org_oswis_core.homepage_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\HomepageWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\HomepageWebController:
        alias: oswis_org_oswis_core.homepage_web_controller
        public: true

    ### Sitemap
    oswis_org_oswis_core.site_map_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\SiteMapWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\SiteMapWebController:
        alias: oswis_org_oswis_core.site_map_web_controller
        public: true

    ### RSS
    oswis_org_oswis_core.rss_feed_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\RssFeedController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\Controller\Website\RssFeedController:
        alias: oswis_org_oswis_core.rss_feed_controller
        public: true

    ### Site WebManifest Web Controller
    oswis_org_oswis_core.site_web_manifest_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\SiteWebManifestController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\SiteWebManifestController:
        alias: oswis_org_oswis_core.site_web_manifest_controller
        public: true

    ### Web Banner Controller
    oswis_org_oswis_core.web_banner_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\WebBannerController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\WebBannerController:
        alias: oswis_org_oswis_core.web_banner_controller
        public: true

    ### Internal Actions Web Controller
    oswis_org_oswis_core.internal_actions_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\InternalActionsWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\InternalActionsWebController:
        alias: oswis_org_oswis_core.internal_actions_web_controller
        public: true

    ### Portal Web Controller
    oswis_org_oswis_core.portal_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\PortalWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\PortalWebController:
        alias: oswis_org_oswis_core.portal_web_controller
        public: true

    ### Admin Web Controller
    oswis_org_oswis_core.admin_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\AdminWebController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\Controller\Website\AdminWebController:
        alias: oswis_org_oswis_core.admin_web_controller
        public: true

    ### GDPR Web Controller
    oswis_org_oswis_core.gdpr_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\GdprWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\GdprWebController:
        alias: oswis_org_oswis_core.gdpr_web_controller
        public: true




    ### Traits folder
    OswisOrg\OswisCoreBundle\Traits\:
        resource: '../../Traits/*'
        public: true

    ### EventSubscriber folder
    OswisOrg\OswisCoreBundle\EventSubscriber\:
        resource: '../../EventSubscriber/*'
        tags: [ { name: 'kernel.view'} ]
        public: true
