# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'cs'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    #    Zakjakub\OswisCoreBundle\:
    #        resource: '../../*'
    #        exclude: '../../{DependencyInjection,Entity,Migrations,Repository,Filter,Tests,Kernel.php}'
    #        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #    Zakjakub\OswisCoreBundle\Filter\SearchFilter:
    #        class: Zakjakub\OswisCoreBundle\Filter\SearchFilter
    #        autowire: true
    #        tags: [ { name: 'api_platform.filter', id: 'search' } ]
    #        public: true

    zakjakub_oswis_core.search_filter:
        class: Zakjakub\OswisCoreBundle\Filter\SearchFilter
        autowire: true
        tags: [ { name: 'api_platform.filter', id: 'search' } ]
        public: true

    Zakjakub\OswisCoreBundle\Filter\SearchFilter:
        alias: zakjakub_oswis_core.search_filter
        public: true


    zakjakub_oswis_core.oswis_core_settings_provider:
        class: Zakjakub\OswisCoreBundle\Provider\OswisCoreSettingsProvider
        autowire: true
        public: true

    Zakjakub\OswisCoreBundle\Provider\OswisCoreSettingsProvider:
        alias: zakjakub_oswis_core.oswis_core_settings_provider
        public: true


    ### AGE UTILS
    zakjakub_oswis_core.oswis_core_age_utils:
        class: Zakjakub\OswisCoreBundle\Utils\AgeUtils
        autowire: true
        public: true
    Zakjakub\OswisCoreBundle\Utils\AgeUtils:
        alias: zakjakub_oswis_core.oswis_core_age_utils
        public: true


    ### COLOR UTILS
    zakjakub_oswis_core.oswis_core_color_utils:
        class: Zakjakub\OswisCoreBundle\Utils\ColorUtils
        autowire: true
        public: true
    Zakjakub\OswisCoreBundle\Utils\ColorUtils:
        alias: zakjakub_oswis_core.oswis_core_color_utils
        public: true


    ### DateTime UTILS
    zakjakub_oswis_core.oswis_core_date_time_utils:
        class: Zakjakub\OswisCoreBundle\Utils\DateTimeUtils
        autowire: true
        public: true
    Zakjakub\OswisCoreBundle\Utils\DateTimeUtils:
        alias: zakjakub_oswis_core.oswis_core_date_time_utils
        public: true


    ### Email UTILS
    zakjakub_oswis_core.oswis_core_email_utils:
        class: Zakjakub\OswisCoreBundle\Utils\EmailUtils
        autowire: true
        public: true
    Zakjakub\OswisCoreBundle\Utils\EmailUtils:
        alias: zakjakub_oswis_core.oswis_core_email_utils
        public: true


    ### File UTILS
    zakjakub_oswis_core.oswis_core_file_utils:
        class: Zakjakub\OswisCoreBundle\Utils\FileUtils
        autowire: true
        public: true
    Zakjakub\OswisCoreBundle\Utils\FileUtils:
        alias: zakjakub_oswis_core.oswis_core_file_utils
        public: true


    ### SourceCode UTILS
    zakjakub_oswis_core.oswis_core_source_code_utils:
        class: Zakjakub\OswisCoreBundle\Utils\SourceCodeUtils
        autowire: true
        public: true
    Zakjakub\OswisCoreBundle\Utils\SourceCodeUtils:
        alias: zakjakub_oswis_core.oswis_core_source_code_utils
        public: true


    ### AGE UTILS
    zakjakub_oswis_core.oswis_core_spam_date_time_encoder:
        class: Zakjakub\OswisCoreBundle\Utils\SpamDateTimeEncoder
        autowire: true
        public: true
    Zakjakub\OswisCoreBundle\Utils\SpamDateTimeEncoder:
        alias: zakjakub_oswis_core.oswis_core_spam_date_time_encoder
        public: true


    ### String UTILS
    zakjakub_oswis_core.oswis_core_source_string_utils:
        class: Zakjakub\OswisCoreBundle\Utils\StringUtils
        autowire: true
        public: true
    Zakjakub\OswisCoreBundle\Utils\StringUtils:
        alias: zakjakub_oswis_core.oswis_core_source_string_utils
        public: true

    zakjakub_oswis_core.app_user_controller:
        class: Zakjakub\OswisCoreBundle\Controller\AppUserController
        autowire: true
        public: true
        arguments:
            - 'doctrine.orm.entity_manager.abstract'
            - 'security.password_encoder'
            - 'monolog.logger'
            - 'mailer'

    Zakjakub\OswisCoreBundle\Controller\AppUserController:
        alias: zakjakub_oswis_core.app_user_controller
        public: true

    zakjakub_oswis_core.index_web_controller:
        class: Zakjakub\OswisCoreBundle\Controller\Website\IndexWebController
        autowire: true
        public: true

    Zakjakub\OswisCoreBundle\Controller\Website\IndexWebController:
        alias: zakjakub_oswis_core.index_web_controller
        public: true

    zakjakub_oswis_core.gdpr_web_controller:
        class: Zakjakub\OswisCoreBundle\Controller\Website\GdprWebController
        autowire: true
        public: true

    Zakjakub\OswisCoreBundle\Controller\Website\GdprWebController:
        alias: zakjakub_oswis_core.gdpr_web_controller
        public: true

    zakjakub_oswis_core.email_sender:
        class: Zakjakub\OswisCoreBundle\Service\EmailSender
        autowire: true
        public: true
        deprecated: true
        arguments:
            - '@swiftmailer.mailer'
            - '@monolog.logger'
            - '@twig'
            - '@zakjakub_oswis_core.oswis_core_settings_provider'
            - '@mailer.mailer'

    Zakjakub\OswisCoreBundle\Service\EmailSender:
        alias: zakjakub_oswis_core.email_sender
        public: true


    Zakjakub\OswisCoreBundle\Manager\:
        resource: '../../Manager/*'
        public: true

    Zakjakub\OswisCoreBundle\Traits\:
        resource: '../../Traits/*'
        public: true

    Zakjakub\OswisCoreBundle\EventSubscriber\:
        resource: '../../EventSubscriber/*'
        tags: [ { name: 'kernel.view'} ]
        # arguments:
        #   ['@security.user_password_encoder.generic', '@doctrine.orm.entity_manager.abstract', '@swiftmailer.mailer.abstract', '@monolog.logger_prototype', '@twig', '@security.token_storage']
        public: true

    Zakjakub\OswisCoreBundle\EventListener\:
        resource: '../../EventListener/*'
        # arguments:
        #   ['@security.user_password_encoder.generic', '@doctrine.orm.entity_manager.abstract', '@swiftmailer.mailer.abstract', '@monolog.logger_prototype', '@twig', '@security.token_storage']
        public: true

    Zakjakub\OswisCoreBundle\Security\AppUserProvider:
        class: Zakjakub\OswisCoreBundle\Security\AppUserProvider
        autowire: true
        public: true
        arguments:
          ['@doctrine.orm.entity_manager.abstract']

    Zakjakub\OswisCoreBundle\Security\:
        resource: '../../Security/*'
        public: true

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
        public: true
    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
        public: true
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
        public: true
    gedmo.listener.iptraceable:
        class: Gedmo\IpTraceable\IpTraceableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
        public: true
