### OSWIS Core - services

parameters:
    locale: 'cs'
    doctrine_behaviors_blameable_user_entity: OswisOrg\OswisCoreBundle\Entity\AppUser

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ### Search Filter
    oswis_org_oswis_core.search_filter:
        class: OswisOrg\OswisCoreBundle\Filter\SearchFilter
        autowire: true
        tags: [ { name: 'api_platform.filter', id: 'search' } ]
        public: true
    OswisOrg\OswisCoreBundle\Filter\SearchFilter:
        alias: oswis_org_oswis_core.search_filter
        public: true

    ### OSWIS Core Settings Provider
    oswis_org_oswis_core.oswis_core_settings_provider:
        class: OswisOrg\OswisCoreBundle\Provider\OswisCoreSettingsProvider
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Provider\OswisCoreSettingsProvider:
        alias: oswis_org_oswis_core.oswis_core_settings_provider
        public: true

    ### AGE UTILS
    oswis_org_oswis_core.oswis_core_age_utils:
        class: OswisOrg\OswisCoreBundle\Utils\AgeUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\AgeUtils:
        alias: oswis_org_oswis_core.oswis_core_age_utils
        public: true

    ### COLOR UTILS
    oswis_org_oswis_core.oswis_core_color_utils:
        class: OswisOrg\OswisCoreBundle\Utils\ColorUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\ColorUtils:
        alias: oswis_org_oswis_core.oswis_core_color_utils
        public: true

    ### DateTime UTILS
    oswis_org_oswis_core.oswis_core_date_time_utils:
        class: OswisOrg\OswisCoreBundle\Utils\DateTimeUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\DateTimeUtils:
        alias: oswis_org_oswis_core.oswis_core_date_time_utils
        public: true

    ### Email UTILS
    oswis_org_oswis_core.oswis_core_email_utils:
        class: OswisOrg\OswisCoreBundle\Utils\EmailUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\EmailUtils:
        alias: oswis_org_oswis_core.oswis_core_email_utils
        public: true

    ### File UTILS
    oswis_org_oswis_core.oswis_core_file_utils:
        class: OswisOrg\OswisCoreBundle\Utils\FileUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\FileUtils:
        alias: oswis_org_oswis_core.oswis_core_file_utils
        public: true

    ### SourceCode UTILS
    oswis_org_oswis_core.oswis_core_source_code_utils:
        class: OswisOrg\OswisCoreBundle\Utils\SourceCodeUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\SourceCodeUtils:
        alias: oswis_org_oswis_core.oswis_core_source_code_utils
        public: true

    ### AGE UTILS
    oswis_org_oswis_core.oswis_core_spam_date_time_encoder:
        class: OswisOrg\OswisCoreBundle\Utils\SpamDateTimeEncoder
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\SpamDateTimeEncoder:
        alias: oswis_org_oswis_core.oswis_core_spam_date_time_encoder
        public: true

    ### String UTILS
    oswis_org_oswis_core.oswis_core_source_string_utils:
        class: OswisOrg\OswisCoreBundle\Utils\StringUtils
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\StringUtils:
        alias: oswis_org_oswis_core.oswis_core_source_string_utils
        public: true

    ### AppUser Controller
    oswis_org_oswis_core.app_user_controller:
        class: OswisOrg\OswisCoreBundle\Controller\AppUserController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.app_user_service'
    OswisOrg\OswisCoreBundle\Controller\AppUserController:
        alias: oswis_org_oswis_core.app_user_controller
        public: true

    ### Homepage Web Controller
    oswis_org_oswis_core.homepage_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\HomepageWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\HomepageWebController:
        alias: oswis_org_oswis_core.homepage_web_controller
        public: true

    ### Sitemap
    oswis_org_oswis_core.site_map_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\SiteMapWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\SiteMapWebController:
        alias: oswis_org_oswis_core.site_map_web_controller
        public: true

    ### RSS
    oswis_org_oswis_core.rss_feed_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\RssFeedController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\Controller\Website\RssFeedController:
        alias: oswis_org_oswis_core.rss_feed_controller
        public: true

    ### Site WebManifest Web Controller
    oswis_org_oswis_core.site_web_manifest_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\SiteWebManifestController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\SiteWebManifestController:
        alias: oswis_org_oswis_core.site_web_manifest_controller
        public: true

    ### Web Banner Controller
    oswis_org_oswis_core.web_banner_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\WebBannerController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\WebBannerController:
        alias: oswis_org_oswis_core.web_banner_controller
        public: true

    ### Internal Actions Web Controller
    oswis_org_oswis_core.internal_actions_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\InternalActionsWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\InternalActionsWebController:
        alias: oswis_org_oswis_core.internal_actions_web_controller
        public: true

    ### Portal Web Controller
    oswis_org_oswis_core.portal_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\PortalWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\PortalWebController:
        alias: oswis_org_oswis_core.portal_web_controller
        public: true

    ### Admin Web Controller
    oswis_org_oswis_core.admin_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\AdminWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\AdminWebController:
        alias: oswis_org_oswis_core.admin_web_controller
        public: true

    ### GDPR Web Controller
    oswis_org_oswis_core.gdpr_web_controller:
        class: OswisOrg\OswisCoreBundle\Controller\Website\GdprWebController
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Controller\Website\GdprWebController:
        alias: oswis_org_oswis_core.gdpr_web_controller
        public: true

    ### AppUser Service
    oswis_org_oswis_core.app_user_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserService
        autowire: true
        public: true
        arguments:
            - '@security.password_encoder'
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@mailer.mailer'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\Service\AppUserService:
        alias: oswis_org_oswis_core.app_user_service
        public: true

    ### AppUser Role Service
    oswis_org_oswis_core.app_user_role_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserRoleService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCoreBundle\Service\AppUserRoleService:
        alias: oswis_org_oswis_core.app_user_role_service
        public: true

    ### AppUser Form Service
    oswis_org_oswis_core.app_user_type_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCoreBundle\Service\AppUserTypeService:
        alias: oswis_org_oswis_core.app_user_type_service
        public: true

    ### AppUser Action Request
    oswis_org_oswis_core.app_user_action_request:
        class: OswisOrg\OswisCoreBundle\Api\Dto\AppUserActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Api\Dto\AppUserActionRequest:
        alias: oswis_org_oswis_core.app_user_action_request
        public: true

    ### AppUser Action Subscriber
    oswis_org_oswis_core.app_user_action_subscriber:
        class: OswisOrg\OswisCoreBundle\Api\EventSubscriber\AppUserActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.app_user_service'
    OswisOrg\OswisCoreBundle\Api\EventSubscriber\AppUserActionSubscriber:
        alias: oswis_org_oswis_core.app_user_action_subscriber
        public: true

    ### Mailer Subscriber
    oswis_org_oswis_core.mailer_subscriber:
        class: OswisOrg\OswisCoreBundle\EventSubscriber\MailerSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\EventSubscriber\MailerSubscriber:
        alias: oswis_org_oswis_core.mailer_subscriber
        public: true

    ### AppUser Subscriber
    oswis_org_oswis_core.app_user_subscriber:
        class: OswisOrg\OswisCoreBundle\EventSubscriber\AppUserSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.app_user_service'
    OswisOrg\OswisCoreBundle\EventSubscriber\AppUserSubscriber:
        alias: oswis_org_oswis_core.app_user_subscriber
        public: true

    ### PDF Generator
    oswis_org_oswis_core.pdf_generator:
        class: OswisOrg\OswisCoreBundle\Service\PdfGenerator
        autowire: true
        public: true
        arguments:
            - '@monolog.logger'
            - '@twig'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\Service\PdfGenerator:
        alias: oswis_org_oswis_core.pdf_generator
        public: true

    ### Traits folder
    OswisOrg\OswisCoreBundle\Traits\:
        resource: '../../Traits/*'
        public: true

    ### EventSubscriber folder
    OswisOrg\OswisCoreBundle\EventSubscriber\:
        resource: '../../EventSubscriber/*'
        tags: [ { name: 'kernel.view'} ]
        # arguments:
        #   ['@security.user_password_encoder.generic', '@doctrine.orm.entity_manager.abstract', '@swiftmailer.mailer.abstract', '@monolog.logger_prototype', '@twig', '@security.token_storage']
        public: true

    ### AppUser Provider
    OswisOrg\OswisCoreBundle\Security\AppUserProvider:
        class: OswisOrg\OswisCoreBundle\Security\AppUserProvider
        autowire: true
        public: true
        arguments:
          ['@doctrine.orm.entity_manager.abstract']

    ### Security folder
    OswisOrg\OswisCoreBundle\Security\:
        resource: '../../Security/*'
        public: true


    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
        public: true

    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
        public: true
