####
#### SERVICES
####
services:

    ### AppUser Service
    oswis_org_oswis_core.app_user_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserService
        autowire: true
        public: true
        arguments:
            - '@security.password_encoder'
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@mailer.mailer'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\Service\AppUserService:
        alias: oswis_org_oswis_core.app_user_service
        public: true

    ### AppUser Role Service
    oswis_org_oswis_core.app_user_role_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserRoleService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCoreBundle\Service\AppUserRoleService:
        alias: oswis_org_oswis_core.app_user_role_service
        public: true

    ### AppUser Form Service
    oswis_org_oswis_core.app_user_type_service:
        class: OswisOrg\OswisCoreBundle\Service\AppUserTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCoreBundle\Service\AppUserTypeService:
        alias: oswis_org_oswis_core.app_user_type_service
        public: true

    ### PDF Generator
    oswis_org_oswis_core.export_service:
        class: OswisOrg\OswisCoreBundle\Service\ExportService
        autowire: true
        public: true
        arguments:
            - '@monolog.logger'
            - '@twig'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\Service\ExportService:
        alias: oswis_org_oswis_core.export_service
        public: true
