services:
    Zakjakub\OswisResourcesBundle\Manager\:
        resource: '../../Manager/*'
        exclude:  '../../Manager/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
