### OSWIS Core - services

imports:
    - { resource: services_services.yaml }
    - { resource: services_subscribers.yaml }
    - { resource: services_utils.yaml }
    - { resource: services_web.yaml }
    - { resource: services_twig.yaml }

parameters:
    locale: 'cs'
    doctrine_behaviors_blameable_user_entity: OswisOrg\OswisCoreBundle\Entity\AppUser

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ### Search Filter
    oswis_org_oswis_core.search_filter:
        class: OswisOrg\OswisCoreBundle\Filter\SearchFilter
        autowire: true
        tags: [ { name: 'api_platform.filter', id: 'search' } ]
        public: true
    OswisOrg\OswisCoreBundle\Filter\SearchFilter:
        alias: oswis_org_oswis_core.search_filter
        public: true

    ### OSWIS Core Settings Provider
    oswis_org_oswis_core.oswis_core_settings_provider:
        class: OswisOrg\OswisCoreBundle\Provider\OswisCoreSettingsProvider
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Provider\OswisCoreSettingsProvider:
        alias: oswis_org_oswis_core.oswis_core_settings_provider
        public: true

    ### SPAM DATE TIME ENCODER
    oswis_org_oswis_core.oswis_core_spam_date_time_encoder:
        class: OswisOrg\OswisCoreBundle\Utils\SpamDateTimeEncoder
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Utils\SpamDateTimeEncoder:
        alias: oswis_org_oswis_core.oswis_core_spam_date_time_encoder
        public: true

    ### AppUser Action Request
    oswis_org_oswis_core.app_user_action_request:
        class: OswisOrg\OswisCoreBundle\Api\Dto\AppUserActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCoreBundle\Api\Dto\AppUserActionRequest:
        alias: oswis_org_oswis_core.app_user_action_request
        public: true

    ### PDF Generator
    oswis_org_oswis_core.export_service:
        class: OswisOrg\OswisCoreBundle\Service\ExportService
        autowire: true
        public: true
        arguments:
            - '@monolog.logger'
            - '@twig'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCoreBundle\Service\ExportService:
        alias: oswis_org_oswis_core.export_service
        public: true

    ### Traits folder
    OswisOrg\OswisCoreBundle\Traits\:
        resource: '../../Traits/*'
        public: true

    ### AppUser Provider
    OswisOrg\OswisCoreBundle\Security\AppUserProvider:
        class: OswisOrg\OswisCoreBundle\Security\AppUserProvider
        autowire: true
        public: true
        arguments:
          ['@doctrine.orm.entity_manager.abstract']

    ### Security folder
    OswisOrg\OswisCoreBundle\Security\:
        resource: '../../Security/*'
        public: true


    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
        public: true

    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
        public: true

