Zakjakub\OswisAccommodationBundle\Entity\Reservation:
    attributes:
        id:
            groups: ['accommodation_reservations_get', 'accommodation_reservation_get']
        createdDateTime:
            groups: ['accommodation_reservations_get', 'accommodation_reservation_get']
        updatedDateTime:
            groups: ['accommodation_reservation_get']
        revision:
            groups: []
        revisions:
            groups: ['accommodation_reservation_get']
        payments:
            groups: ['accommodation_reservation_get']
        depositValue:
            groups: ['accommodation_reservations_get', 'accommodation_reservation_get']
        usedDiscounts:
            groups: ['accommodation_reservation_get', 'accommodation_reservation_get', 'accommodation_reservation_put']
        paidValue:
            groups: ['accommodation_reservations_get', 'accommodation_reservation_get']
        totalPrice:
            groups: ['accommodation_reservations_get', 'accommodation_reservation_get']
        prices:
            groups: ['accommodation_reservation_get']
        note:
            groups: ['accommodation_reservation_get', 'accommodation_reservation_put']
        subReservations:
            groups: ['accommodation_reservation_get', 'accommodation_reservation_put']
        lastUpdateDateTime:
            groups: ['accommodation_reservations_get', 'accommodation_reservation_get']

Zakjakub\OswisAccommodationBundle\Entity\ReservationRev:
    attributes:
        id:
            groups: ['accommodation_reservation_get']
        createdDateTime:
            groups: ['accommodation_reservation_get']
        updatedDateTime:
            groups: ['accommodation_reservation_get']
        note:
            groups: ['accommodation_reservation_get']
        usedDiscounts:
            groups: ['accommodation_reservation_get']
        subReservations:
            groups: ['accommodation_reservation_get']
        totalPrice:
            groups: ['accommodation_reservation_get']
        prices:
            groups: ['accommodation_reservation_get']

