
App\Entity\Accommodation\PersonCategory:
    attributes:
        id:
            groups: ['person_categories_get', 'person_category_get']
        name:
            groups: ['person_categories_get', 'person_categories_post', 'person_category_get', 'person_category_put']
        shortName:
            groups: ['person_categories_get', 'person_categories_post', 'person_category_get', 'person_category_put']
        createdDateTime:
            groups: ['person_category_get']
        updatedDateTime:
            groups: ['person_category_get']
        description:
            groups: ['person_categories_post', 'person_category_get', 'person_category_put']
        note:
            groups: ['person_categories_post', 'person_category_get', 'person_category_put']
        deleted:
            groups: ['person_categories_get', 'person_categories_post', 'person_category_get', 'person_category_put']

App\Entity\Accommodation\RoomCategoryPrice:
    attributes:
        id:
            groups: ['person_category_get']





