
App\Entity\Accommodation\RoomCategory:
    attributes:
        id:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_period_get'
        name:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'
        shortName:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'
        createdDateTime:
            groups:
                - 'accommodation_special_period_get'
        updatedDateTime:
            groups:
                - 'accommodation_special_period_get'
        description:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'
        note:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'
        startDateTime:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'
        endDateTime:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'
        facilities:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'
        rooms:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'
        reason:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'
        accommodationNotAvailable:
            groups:
                - 'accommodation_special_periods_get'
                - 'accommodation_special_periods_post'
                - 'accommodation_special_period_get'
                - 'accommodation_special_period_put'

App\Entity\Accommodation\Room:
    attributes:
        id:
            groups:
                - 'accommodation_special_period_get'
        name:
            groups:
                - 'accommodation_special_period_get'

App\Entity\Accommodation\Facility:
    attributes:
        id:
            groups:
                - 'accommodation_special_period_get'
        name:
            groups:
                - 'accommodation_special_period_get'

