OswisOrg\OswisCoreBundle\Interfaces\Common\ActivatedInterface:
    attributes:
        activated:
            groups:
                - 'entities_get'
                - 'entities_post'
                - 'entity_get'
                - 'entity_put'
