OswisOrg\OswisCoreBundle\Entity\AppUser\AppUserType:
    attributes:
        id:
            groups: [ 'app_user_types_get', 'app_user_type_get' ]
        adminUser:
            groups: [ 'app_user_types_get', 'app_user_types_post', 'app_user_type_get', 'app_user_type_put' ]
        createdAt:
            groups: [ 'app_user_type_get' ]
        updatedAt:
            groups: [ 'app_user_type_get' ]
        appUserRole:
            groups: [ 'app_user_types_post', 'app_user_type_get', 'app_user_type_put' ]
        roleName:
            groups: [ 'app_user_types_get', 'app_user_type_get' ]

OswisOrg\OswisCoreBundle\Entity\AppUser\AppUserRole:
    attributes:
        id:
            groups: [ 'app_user_types_post', 'app_user_type_get', 'app_user_type_put' ]
        name:
            groups: [ 'app_user_type_get' ]
        roleName:
            groups: [ 'app_user_type_get' ]
        roleString:
            groups: [ 'app_user_type_get' ]
        parent:
            groups: [ 'app_user_type_get' ]





