# /config/serialization/AppUser.yaml
OswisOrg\OswisCoreBundle\Entity\AppUser:
    attributes:
        username:
            groups: ['app_users_get', 'app_users_post', 'app_user_get', 'app_user_put']
        email:
            groups: ['app_users_get', 'app_users_post', 'app_user_get', 'app_user_put']
        active:
            groups: ['app_users_get', 'app_user_get']
        adminUser:
            groups: ['app_users_get', 'app_users_post', 'app_user_get', 'app_user_put']
        fullName:
            groups: ['app_users_get', 'app_users_post', 'app_user_get', 'app_user_put']
        appUserType:
            groups: ['app_users_get', 'app_user_get']
        startDateTime:
            groups: ['app_users_get', 'app_users_post', 'app_user_get', 'app_user_put']
        endDateTime:
            groups: ['app_users_get', 'app_user_get', 'app_user_put']
        roles:
            groups: ['app_user_get']

OswisOrg\OswisCoreBundle\Entity\AppUserType:
    attributes:
        id:
            groups: ['app_users_post', 'app_user_put']
        roleName:
            groups: ['app_user_get']

