OswisOrg\OswisCoreBundle\Interfaces\Common\BasicInterface:
    attributes:
        id:
            groups:
                - 'entities_get'
                - 'entity_get'
        customId:
            groups:
                - 'entities_get'
                - 'entities_post'
                - 'entity_get'
        createdAt:
            groups:
                - 'entities_get'
                - 'entity_get'
        updatedAt:
            groups:
                - 'entities_get'
                - 'entity_get'
        createdBy:
            groups:
                - 'entity_get'
        updatedBy:
            groups:
                - 'entity_get'
