OswisOrg\OswisCoreBundle\Entity\Logger\ClientLogRecord:
    attributes:
        level:
            groups: ['client_log_records_post']
        message:
            groups: ['client_log_records_post']
