OswisOrg\OswisCoreBundle\Interfaces\Common\NameableInterface:
    attributes:
        slug:
            groups:
                - 'nameables_get'
                - 'nameable_get'
        forcedSlug:
            groups:
                - 'nameables_get'
                - 'nameables_post'
                - 'nameable_get'
                - 'nameable_put'
        name:
            groups:
                - 'nameables_get'
                - 'nameables_post'
                - 'nameable_get'
                - 'nameable_put'
        shortName:
            groups:
                - 'nameables_get'
                - 'nameables_post'
                - 'nameable_get'
                - 'nameable_put'
        description:
            groups:
                - 'nameables_get'
                - 'nameables_post'
                - 'nameable_get'
                - 'nameable_put'
        note:
            groups:
                - 'nameables_get'
                - 'nameables_post'
                - 'nameable_get'
                - 'nameable_put'
        internalNote:
            groups:
                - 'nameables_get'
                - 'nameables_post'
                - 'nameable_get'
                - 'nameable_put'

