OswisOrg\OswisCoreBundle\Interfaces\Common\NameableInterface:
    attributes:
        slug:
            groups:
                - 'entities_get'
                - 'entity_get'
        forcedSlug:
            groups:
                - 'entities_get'
                - 'entities_post'
                - 'entity_get'
                - 'entity_put'
        name:
            groups:
                - 'entities_get'
                - 'entities_post'
                - 'entity_get'
                - 'entity_put'
        shortName:
            groups:
                - 'entities_get'
                - 'entities_post'
                - 'entity_get'
                - 'entity_put'
        description:
            groups:
                - 'entities_get'
                - 'entities_post'
                - 'entity_get'
                - 'entity_put'
        note:
            groups:
                - 'entities_get'
                - 'entities_post'
                - 'entity_get'
                - 'entity_put'
        internalNote:
            groups:
                - 'entities_get'
                - 'entities_post'
                - 'entity_get'
                - 'entity_put'

