OswisOrg\OswisCoreBundle\Interfaces\Common\PriorityInterface:
    attributes:
        priority:
            groups:
                - 'entities_get'
                - 'entities_post'
                - 'entity_get'
                - 'entity_put'
